<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, fm, call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT fm (device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl, setvol, at)>
  <!ELEMENT alsa_device EMPTY>
  <!ATTLIST alsa_device name (music|FM|voice|aux|voice-call|bt-voice-call) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT alsa_device EMPTY>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ELEMENT pcm_config EMPTY>
  <!ELEMENT device EMPTY>
  <!ATTLIST device name (speaker|headphone|headset|earpiece|dualmic-earpiece|bt-sco|aux|builtin-mic|back-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call) #REQUIRED>
  <!ELEMENT device EMPTY>
  <!ELEMENT path EMPTY>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT path EMPTY>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
  <!ELEMENT setvol EMPTY>
  <!ATTLIST setvol name CDATA #REQUIRED>
  <!ATTLIST setvol count CDATA #REQUIRED>
  <!ATTLIST setvol val0 CDATA #REQUIRED>
  <!ATTLIST setvol val1 CDATA #REQUIRED>
  <!ATTLIST setvol val2 CDATA #REQUIRED>
  <!ATTLIST setvol val3 CDATA #REQUIRED>
  <!ATTLIST setvol val4 CDATA #REQUIRED>
  <!ATTLIST setvol val5 CDATA #REQUIRED>
  <!ELEMENT setvol EMPTY>
  <!ELEMENT at EMPTY>
  <!ATTLIST at node CDATA #REQUIRED>
  <!ATTLIST at cmd CDATA #REQUIRED>
  <!ELEMENT at EMPTY>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>
  <alsa_device name="music"
               card_id="-1"
               card_name="tegramax9809X"
               device_id="0">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>

    <param name="ulp" val="1"/>
    <param name="HW Rates" val="48000"/>
    <param name="nvoice" val="0"/>
    <param name="I2S Master" val="1"/>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="Headphone Volume" val="16"/>
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="headset">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="Headphone Volume" val="16"/>
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="Speaker Volume" val="23"/>
		  <ctl name="Playback Volume" val="3"/>
          <ctl name="Right Speaker Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC1 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Right Speaker Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Right Speaker Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="Receiver Volume" val="21"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Receiver Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
     <device name="dualmic-earpiece">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="Receiver Volume" val="21"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Receiver Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
	  <device name="bt-sco">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
        </path>
        <path name="off">
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="MIC1 Volume" val="20"/>
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="ADCL Volume" val="15"/>
          <ctl name="ADCL Boost Volume" val="1"/>
          <ctl name="ADCR Volume" val="15"/>
          <ctl name="ADCR Boost Volume" val="1"/>
          <ctl name="External MIC" val="None"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
        </path>
      </device>
      <device name="back-mic">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="MIC2 Volume" val="20"/>
          <ctl name="MIC2 Boost Volume" val="0"/>
          <ctl name="ADCL Volume" val="15"/>
          <ctl name="ADCL Boost Volume" val="1"/>
          <ctl name="ADCR Volume" val="15"/>
          <ctl name="ADCR Boost Volume" val="1"/>
          <ctl name="External MIC" val="None"/>
          <ctl name="Left ADC Mixer MIC2 Switch" val="1"/>          
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC2 Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="MIC2 Volume" val="20"/>
          <ctl name="MIC2 Boost Volume" val="0"/>
          <ctl name="ADCL Volume" val="15"/>
          <ctl name="ADCL Boost Volume" val="1"/>
          <ctl name="ADCR Volume" val="15"/>
          <ctl name="ADCR Boost Volume" val="1"/>
		  <ctl name="SPK_Head MIC Switch" val="1"/>
          <ctl name="External MIC" val="MIC2"/>
          <ctl name="Left ADC Mixer MIC2 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC2 Switch" val="0"/>
          <ctl name="External MIC" val="None"/>
        </path>
      </device>
      <device name="spk-mic">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI1"/>
          <ctl name="MIC2 Volume" val="20"/>
          <ctl name="MIC2 Boost Volume" val="0"/>
          <ctl name="ADCL Volume" val="15"/>
          <ctl name="ADCL Boost Volume" val="1"/>
          <ctl name="ADCR Volume" val="15"/>
          <ctl name="ADCR Boost Volume" val="1"/>
		  <ctl name="SPK_Head MIC Switch" val="0"/>
          <ctl name="External MIC" val="MIC2"/>
          <ctl name="Left ADC Mixer MIC2 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC2 Switch" val="0"/>
          <ctl name="External MIC" val="None"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="FM"
               card_id="-1"
               card_name="tegramax9809X"
               device_id="8">

    <fm>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Volume" val="16"/>
          <ctl name="Linein Volume" val="4"/>
          <ctl name="Left Headphone Mixer IN1 Switch" val="1"/>
          <ctl name="Right Headphone Mixer IN2 Switch" val="1"/>
          <ctl name="FM Mode Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Left Headphone Mixer IN1 Switch" val="0"/>
          <ctl name="Right Headphone Mixer IN2 Switch" val="0"/>
          <ctl name="FM Mode Switch" val="0"/>
        </path>
      </device>
      <device name="headset">
        <path name="on">
          <ctl name="Headphone Volume" val="16"/>
          <ctl name="Linein Volume" val="4"/>
          <ctl name="Left Headphone Mixer IN1 Switch" val="1"/>
          <ctl name="Right Headphone Mixer IN2 Switch" val="1"/>
          <ctl name="FM Mode Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Left Headphone Mixer IN1 Switch" val="0"/>
          <ctl name="Right Headphone Mixer IN2 Switch" val="0"/>
          <ctl name="FM Mode Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Speaker Volume" val="17"/>
          <ctl name="Linein Volume" val="5"/>
          <ctl name="Right Speaker Mixer IN1 Switch" val="1"/>
          <ctl name="Right Speaker Mixer IN2 Switch" val="1"/>
          <ctl name="FM Mode Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Right Speaker Mixer IN1 Switch" val="0"/>
          <ctl name="Right Speaker Mixer IN2 Switch" val="0"/>
          <ctl name="FM Mode Switch" val="0"/>
        </path>
      </device>
    </fm>
  </alsa_device>

  <alsa_device name ="aux"
             card_id="-1"
             card_name="Tegra"
             device_id="3">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <playback>
      <device name="aux"/>
    </playback>
  </alsa_device>

  <alsa_device name="wfd">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"/>
    <playback>
      <device name="wfd"/>
    </playback>
  </alsa_device>

  <alsa_device name ="voice-call"
           card_id="-1"
           card_name="tegramax9809X"
           device_id="1">
    <pcm_config rate="8000"
            channels="1"
            bps="16"
            period_size="256"
                period_count="4"
            start_threshold="1023"
            stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Flexsound" val="OFF"/>
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <device name="headphone">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCL Boost Volume" val="0"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="ADCR Boost Volume" val="0"/>
          <ctl name="MIC1 Volume" val="18"/>
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="Flexsound" val="WHS_MIC"/>
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="1"/>
          <ctl name="External MIC" val="None"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>
          <setvol name="Headphone Volume" count="6" val0="14" val1="16" val2="18" val3="20" val4="23" val5="25"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="headset">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCL Boost Volume" val="0"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="ADCR Boost Volume" val="0"/>
          <ctl name="MIC1 Volume" val="18"/>
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="Flexsound" val="WHS"/>
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="1"/>
          <ctl name="External MIC" val="MIC1"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>		  
          <setvol name="Headphone Volume" count="6" val0="14" val1="16" val2="18" val3="20" val4="23" val5="25"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
          <ctl name="External MIC" val="None"/>
          <ctl name="Left Headphone Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCL Boost Volume" val="0"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="ADCR Boost Volume" val="0"/>		  
          <ctl name="MIC2 Boost Volume" val="0"/>
          <ctl name="MIC2 Volume" val="18"/>
          <ctl name="SPK_Head MIC Switch" val="0"/>
          <ctl name="Flexsound" val="SPK"/>
          <ctl name="Right Speaker Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC1 Switch" val="1"/>
          <ctl name="External MIC" val="MIC2"/>	
          <ctl name="Left ADC Mixer MIC2 Switch" val="1"/>
          <setvol name="Speaker Volume" count="6" val0="15" val1="16" val2="17" val3="18" val4="20" val5="22"/>
        </path>
        <path name="off">
          <ctl name="SPK_Head MIC Switch" val="1"/>
          <ctl name="Left ADC Mixer MIC2 Switch" val="0"/>
          <ctl name="Right Speaker Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Right Speaker Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCL Boost Volume" val="0"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="ADCR Boost Volume" val="0"/>		  
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="MIC1 Volume" val="18"/>
          <ctl name="Flexsound" val="RCV1"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="1"/>
          <ctl name="External MIC" val="None"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>
          <setvol name="Receiver Volume" count="6" val0="15" val1="17" val2="19" val3="20" val4="22" val5="24"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="dualmic-earpiece">
        <path name="on">
		  <ctl name="ADCDAI Switch" val="DAI2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCL Boost Volume" val="0"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="ADCR Boost Volume" val="0"/>
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="MIC1 Volume" val="18"/>
          <ctl name="MIC2 Boost Volume" val="0"/>
          <ctl name="MIC2 Volume" val="18"/>
          <ctl name="Flexsound" val="RCV2"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="1"/>
          <ctl name="External MIC" val="None"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>
          <ctl name="Right ADC Mixer MIC2 Switch" val="1"/>
          <setvol name="Receiver Volume" count="6" val0="15" val1="17" val2="19" val3="20" val4="22" val5="24"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
          <ctl name="Right ADC Mixer MIC2 Switch" val="0"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
      <device name="loop-earpiece">
        <path name="on">
          <ctl name="ADCDAI Switch" val="DAI2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCL Boost Volume" val="0"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="ADCR Boost Volume" val="0"/>		  
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="MIC1 Volume" val="20"/>
          <ctl name="Flexsound" val="RCV1"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="1"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="1"/>
          <ctl name="External MIC" val="None"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>
          <setvol name="Receiver Volume" count="6" val0="16" val1="17" val2="18" val3="19" val4="21" val5="23"/>
        </path>
        <path name="off">
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
          <ctl name="Receiver Mixer Left DAC1 Switch" val="0"/>
          <ctl name="Receiver Mixer Right DAC1 Switch" val="0"/>
        </path>
      </device>
    </call>
    <call>
      <device name="builtin-mic">
        <path name="on">
        </path>
        <path name="off">
        </path>
      </device>
	  <device name="back-mic">
        <path name="on">
        </path>
        <path name="off">
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
        </path>
        <path name="off">
        </path>
      </device>
    </call>
  </alsa_device>

  <alsa_device name ="bt-voice-call"
               card_id="-1"
           card_name="tegramax9809X"
           device_id="2"
           second_device_id="1">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <second_pcm_config rate="8000"
            channels="1"
            bps="16"
            period_size="256"
            period_count="4"
            start_threshold="1023"
            stop_threshold="1024"
            silence_threshold="0"
            avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <device name="bt-sco">
        <path name="on">
          <ctl name="Flexsound" val="OFF"/>
          <ctl name="ADCDAI Switch" val="DAI2"/>
          <ctl name="ADCSRC Switch" val="1"/>
          <ctl name="SRC3DAI2 Switch" val="1"/>
          <ctl name="SRC2DAI3 Switch" val="1"/>
          <ctl name="SRC3DAI1 Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="ADCSRC Switch" val="0"/>
          <ctl name="SRC3DAI2 Switch" val="0"/>
          <ctl name="SRC2DAI3 Switch" val="0"/>
          <ctl name="SRC3DAI1 Switch" val="0"/>
        </path>
      </device>
    </call>
    <call>
      <device name="bt-sco-mic">
        <path name="on">
        </path>
        <path name="off">
        </path>
      </device>
    </call>
  </alsa_device>
</AudioConfigs>
